config/routes.rb
Organize::Application.routes.draw do

  root to: "contents#root"

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/:provider', :to => 'sessions#create', as: :create_session

  resources :contents, only: [:show, :index, :new, :create] do
    post :suggest_for
    post :add_to
    post :add_mine
    post :rate
  end

  resources :users do
    resources :contents, only: [:index]
  end

  resources :spaces do
    resources :contents, only: [:index]
  end

  resources :comments, only: [:create]

end

app/models/content.rb
# coding: utf-8
class Content < ActiveRecord::Base
  validates :name, presence: true
  validates :kind, presence: true
  validates :link, presence: true, uniqueness: true

  belongs_to :owner, class_name: "User", foreign_key: "user_id"

  has_one :space_content_association, dependent: :destroy
  has_one :space, through: :space_content_association

  has_many :user_content_associations, dependent: :destroy
  has_many :users, through: :user_content_associations
  has_many :comments

  attr_accessible :space_content_association, :link, :name,
    :kind, :description, :study_estimated_time

  classy_enum_attr :kind
  has_reputation :rating, source: :user, aggregated_by: :average
  MIN_RATING = 1
  MAX_RATING = 5

  def suggest!
    self.space_content_association.update_attributes({ status: 'suggested' })
  end

  def accept!
    self.space_content_association.update_attributes({ status: 'accepted' })
  end

  def reject!
    self.space_content_association.destroy
  end

  def belongs_to_space?(space)
    self.space.try(:id) == space.id
  end

  def belongs_to_user?(user)
    self.users.include?(user)
  end

  def self.is_valid_rating_value?(value)
    value.between?(MIN_RATING, MAX_RATING)
  end

  def get_rating_by(user)
    self.evaluations.where(source_id: user.id, source_type: "User",
                           reputation_name: "rating").first.value
  end

  def study_estimated_time
    time = read_attribute(:study_estimated_time)
    hour = time / 60
    minute = time % 60

    if (hour == 0 && minute == 0)
      "Desconhecido"
    else
      if hour > 0
        hour = "#{hour} horas "
      else
        hour = ""
      end

      if minute > 0
        minute = "#{minute} minutos"
      else
        minute = ""
      end

      "#{hour}#{minute}"
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def root
    current_space
    client = ReduClient.new(current_user.token, current_space.uid)
    client.update_role(current_user.uid)
    redirect_to contents_path
  end

  def index
    if params[:space_id]
      @user = current_user
      @space = current_space
      @contents = @space.contents
      @suggestions = @space.suggestions
    else
      @user = current_user
      @contents = @user.contents
    end

    if params[:bests]
      reputations = Content.find_with_reputation(:rating, :all, order: 'rating desc')
      @contents = reputations & @contents
    elsif params[:time]
      @contents = @contents.order(:study_estimated_time)
    else
      @contents = @contents.order(:created_at).reverse_order
    end
  end

  def show
    @content = Content.find(params[:id].to_s)
    @content_rating = @content.reputation_for(:rating)
    @evaluations = @content.evaluators_for(:rating).count
    @evaluated = @content.has_evaluation?(:rating, current_user)
    @user_rating = @content.get_rating_by(current_user) if @evaluated
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(params[:content])
    @user = current_user
    @content.owner = @user

    if @content.save
      flash[:notice] = "O link <strong>#{@content.name}</strong> foi adicionado."

      if params[:add_link_to_space]
        Space.find(params[:space_id].to_s).contents << @content
        @content.accept!

        if params[:post_wall]
          client = ReduClient.new(current_user.token, current_space.uid)
          client.post_wall_space(params[:redu_lecture_id])
        end

        redirect_to space_contents_path(current_space)
      else
        @user.contents << @content
        redirect_to contents_path
      end
    else
      render 'new'
    end
  end

  def suggest_for
    @content = Content.find(params[:content_id].to_s)
    @space = current_space

    unless @content.belongs_to_space? @space
      @space.contents << @content
      @content.suggest!
    end

    respond_to do |format|
      format.js do
        render 'contents/confirm_suggest'
      end
    end
  end

  def add_mine
    @content = Content.find(params[:content_id].to_s)
    @user = current_user
    @user.contents << @content

    flash[:notice] = "O link <strong>#{@content.name}</strong> foi adicionado aos seus links."
    redirect_to content_path(@content)
  end

  def add_to
    @content = Content.find(params[:content_id].to_s)
    @contents = current_space.contents

    case params[:commit]
    when "recusar"
      @content.reject!
    when "aceitar"
      @content.accept!
    end

    respond_to do |format|
      format.js do
        render 'contents/moderate_suggestion'
      end
    end
  end

  def rate
    rating = Integer(params[:rating])
    @content = Content.find(params[:content_id])
    @content.add_or_update_evaluation(:rating, rating, current_user)
    @user_rating = rating
    @content_rating = @content.reputation_for(:rating)
    @evaluated = true
    @evaluations = @content.evaluators_for(:rating).count

    respond_to do |format|
      format.js
    end
  end
end

app/views/contents/_list.html.erb
<%# Lista de disciplinas

  Variáveis:
    - contents: links pertecentes à lista
%>
<ul class="list-button list-subject">
  <% contents.each do |content| %>
    <li class="list-button-item link-container">
      <%# TODO: Diferenciar ícone dependendo do tipo de link. %>
      <%= link_to content.name, content_path(content), :class => "list-button-link link-target icon-text-page-lightblue_16_18-before" %>
      <div class="list-lecture-info">
        <%= content_tag(:span, content.comments.size, :rel => "tooltip", :title => pluralize(content.comments.size, "Comentário"), :class => "wall-stats icon-wall-gray_16_18-before") %>
        <%# Rating. %>
        <%= render "shared/content_rating_stars", rating: content.reputation_for(:rating).to_i %>
        <%= content_tag :span, content.study_estimated_time, :rel => "tooltip", :title => "Tempo estimado de estudo" %>
      </div>
    </li>
  <% end %>
</ul>

app/views/contents/_star.html.erb
<%#
    Renderiza uma estrela.
    Caso algum usuário estiver logado, a estrela é clicável para o voto. Caso contrário a estrela é apenas mostrada.

    Variáveis locais:
    index: indica o número ordenal da estrela.
    type: indica o tipo de estrela (lightgray, gray ou blue).
  %>
<li class="oer-star">
  <%= link_to "#{index+1}", content_rate_path(@content, rating: index+1), method: "post", remote: true, class: "icon-star-full-" + type + "_16_18 show text-replacement", "data-star-color" => type %>
</li>

app/views/contents/_stars.html.erb
<div class="oer-rating">
  <div class="oer-stars-n-value">
    <%# Estrelas. %>
    <ol class="oer-stars<%= " oer-stars-user-rated" %>">
      <% user_rating = @user_rating.to_i || 0 %>
      <% index = user_rating || 0 %>
      <%# Renderiza as estrelas azuis da nota do usuário. %>
      <% user_rating.times do |n| %>
        <%= render "star", index: n, type: "blue" %>
      <% end %>
      <%# Renderiza as estrelas cinza escuro da média de classificação. %>
      <% if @content_rating > user_rating %>
        <% (@content_rating - user_rating).to_i.times do |n| %>
          <%= render "star", index: index, type: "gray" %>
          <% index += 1 %>
        <% end %>
      <% end %>
      <%# Renderiza as estrelas cinza claro restantes. %>
      <% (5 - index).times do |n| %>
        <%= render "star", index: index, type: "lightgray" %>
        <% index += 1 %>
      <% end %>
    </ol>
</div>

app/views/contents/confirm_suggest.js.erb
$("body").append('<div class="system-message message-success"><span data-dismiss="alert" class="message-close">×</span><p>Seu link foi sugerido à lista da Disciplina</p></div>');
$(".button-success").remove();
$(".system-message").delay(3000).fadeOut(1000, "linear");

app/views/contents/index.html.erb
<% content_for :title do %>
  <% if @space %>
    Links da Disciplina
  <% else %>
    Meus links
  <% end %>
<% end %>

<%# Lista de links. %>
<% if @contents.size > 0 %>
  <%= render :partial => "shared/sub-tabs" %>
  <hr class="list-separator">
  <div class="content-section">
    <% if @user.teacher? && @space %>
      <ul class="list-mix suggestions">
        <% @suggestions.each do |suggestion| %>
          <li class="list-mix-item" id="<%= suggestion.id %>">
            <div class="list-mix-inner">
              <span><%= suggestion.owner.name %> indicou o seguinte conteúdo para a disciplina</span>
              <%= link_to "Recusar", content_add_to_path(content_id: suggestion, commit: "recusar"),
                class: "button-danger pull-right", method: :post, remote: true %>
              <%= link_to "Aceitar", content_add_to_path(content_id: suggestion, commit: "aceitar"),
                class: "button-success pull-right", method: :post, remote: true %>
              <%= link_to suggestion.name, content_path(suggestion) %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
    <%= render "list", contents: @contents %>
  </div>
<%# Nenhum link criado. %>
<% else %>
  <div class="content-section">
    <%= render "shared/message-block", :type => "info", :close => false, :message => "#{subject(@space)} ainda não possui nenhum link.", :button => nil %>
  </div>
<% end %>

app/views/contents/moderate_suggestion.js.erb
$("#<%= @content.id %>").slideToggle();
var $list = $(".list-button");
var $newList = $("<%= escape_javascript render 'contents/list', contents: @contents %>");
$list.replaceWith($newList);

app/views/contents/new.html.erb
<% content_for :title do %>
  Adicionar link
<% end %>

<div class="content-section">
  <%= form_for(@content, url: contents_path, :html => { :class => "form-horizontal" }) do |f| %>

    <%# Tipo de material. %>
    <div class="control-group row">
      <div class="control-label span4">
        <%= f.label :kind, "Tipo de material" %>:
      </div>
      <div class="controls span6">
        <%= f.select :kind, options_for_select( Kind.all.collect { |s| [s.text, s] }, :selected => f.object.name) %>
        <span class="legend">Escolha o tipo de material que o link representa</span>
        <%= concave_errors_for(f.object, :kind) %>
      </div>
    </div>

    <%# Link. %>
    <div class="control-group row">
      <div class="control-label span4">
        <%= f.label :link, "Link" %>:
      </div>
      <div class="controls span6">
        <%= f.text_field :link, :placeholder => "Cole o link aqui" %>
        <%= concave_errors_for(f.object, :link) %>
      </div>
    </div>

    <%# Título. %>
    <div class="control-group row">
      <div class="control-label span4">
        <%= f.label :name, "Título" %>
      </div>
      <div class="controls span6">
        <%= f.text_field :name, :placeholder => "Dê um título representativo para o link" %>
        <%= concave_errors_for(f.object, :name) %>
      </div>
    </div>

    <%# Descrição. %>
    <div class="control-group row">
      <div class="control-label span4">
        <%= f.label :description, "Descrição" %>:
      </div>
      <div class="controls span6">
        <%= f.text_area :description, :placeholder => "Descreva brevemento do que se trata o link", :rows => 5 %>
      </div>
    </div>

    <%# Tempo estimado de estudo. %>
    <div class="control-group row">
      <div class="control-label span4">
        <%= f.label :study_estimated_time, "Tempo estimado de estudo" %>:
      </div>
      <div class="controls span6">
        <div class="row">
          <%= select_tag(:study_estimated_time_hour, options_for_select((0..12).to_a), :class => "span2") %>
          <span class="span1 legend time-legend">horas</span>
          <%= select_tag(:study_estimated_time_minute, options_for_select((0..60).to_a), :class => "span2") %>
          <span class="span1 legend time-legend">minutos</span>
        </div>
        <span class="legend">Sugira um tempo médio necessário para estudar conteúdo do link</span>
        <%= f.hidden_field :study_estimated_time %>
      </div>
    </div>

    <% if current_user.teacher? %>
      <div class="control-group row">
        <div class="controls span6 offset4">
          <label class="control-checkbox" rel="tooltip" title="Marcando esta opção o link será adicionado à disciplina ao invés da lista pessoal">
            <%= check_box_tag(:add_link_to_space) %> Adicionar link à disciplina.
          </label>
          <label class="control-checkbox" id="post-wall" rel="tooltip" title="Marcando esta opção o link será publicado no Mural da Disciplina se a opção acima também tiver sido marcada">
            <%= check_box_tag(:post_wall) %> Postar no mural da Disciplina.
          </label>
          <%= hidden_field_tag :space_id, current_space.id %>
        </div>
      </div>
    <% end %>

    <%# TODO: Visibilidade. %>

    <div class="control-group row">
      <div class="span10">
        <%= f.submit "Adicionar", :class => "button-primary pull-right", :rel => "tooltip", :title => "Adicionar o link", :disabled => true %>
        <%= button_tag "Limpar", :type => :reset, :class => "button-default pull-right", :rel => "tooltip", :title => "Limpar os campos do formulário" %>
      </div>
    </div>
  <% end %>
</div>

app/views/contents/rate.js.erb
$('.oer-rating').html('<%= escape_javascript render partial: "stars" %>');
$('#evaluation-count').html('<%= t 'evaluation', count: @evaluations %>');

app/views/contents/show.html.erb
<% content_for :title do %>
  Link
<% end %>

<div class="content-section content-title clearfix">
  <div class="clearfix">
    <%= link_to 'Voltar', :contents, class: "button-default pull-left back" %>
    <% unless @content.belongs_to_space? current_space %>
      <%= link_to "Sugerir como link da discplina", content_suggest_for_path(content_id: params[:id]),
        class: "button-success pull-right", method: :post, remote: true %>
    <% end %>
    <% unless @content.belongs_to_user? current_user %>
      <%= link_to "Adicionar aos Meus Links", content_add_mine_path(content_id: params[:id]),
        class: "button-success pull-right", method: :post %>
    <% end %>
  </div>
  <h3 class="pull-left"><%= @content.name %></h3>
  <ul class="content-rating pull-left">
    <%= render partial: "stars" %>
  </ul>
</div>
<hr class="list-separator">
<div class="content-section clearfix">
  <ul class="content-details">
    <li class="icon-file-lightblue_16_18-before">
      <%= link_to @content.link, @content.link, target: "_blank", title: @content.name %>
    </li>
    <% if @content.description %>
      <li><span class="icon-doubt-topic-lightblue_16_18-before show text-replacement pull-left">Detalhes</span><p class="pull-left"><%= @content.description %></p></li>
    <% end %>
    <li class="icon-clock-lightblue_16_18-before"><%= @content.study_estimated_time or 'Tempo não informado' %></li>
  </ul>
</div>
<hr class="list-separator">
<div class="content-section content-comments clearfix">
  <h6 class="icon-comment-gray_16_18-before">Comentários</h6>
  <div class="create-response post">
    <%= form_for(:comment, url: comments_path) do |f|%>
      <%= f.text_field :body %><br />
      <%= hidden_field_tag :content_id, params[:id] %>
      <div class="status-buttons">
        <%= f.submit 'Postar', class: 'button-primary pull-right' %>
      </div>
    <% end %>
  </div>
  <% @content.comments.each do |comment| %>
    <div class="create-response comment">
      <b><%= comment.author.name %></b>
      <p class="post-description"><%= comment.body %></p>
    </div>
  <% end %>
</div>