config/routes.rb
Organize::Application.routes.draw do

  root to: "contents#root"

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/:provider', :to => 'sessions#create', as: :create_session

  resources :contents, only: [:show, :index, :new, :create] do
    post :suggest_for
    post :add_to
    post :add_mine
    post :rate
  end

  resources :users do
    resources :contents, only: [:index]
  end

  resources :spaces do
    resources :contents, only: [:index]
  end

  resources :comments, only: [:create]

end

app/views/shared/_content_rating_stars.html.erb
<% if rating > 0 %>
    <% rating.times do %>
      <span class="star icon-star-full-gray_8_10 show text-replacement">Estrela</span>
    <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="system-message message-success fade in">
    <span data-dismiss="alert" class="message-close">×</span>
    <p><strong>Muito bem!</strong> <%= raw(flash[:notice]) %></p>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="content-section">
  <ul class="header-breadcrumb">
    <li class="header-breadcrumb-item">
      <h2 class="header-title"><%= yield :title %></h2>
    </li>
  </ul>
  <%= link_to "Adicionar link", new_content_path, class: "button-primary pull-right", rel: "tooltip", title: "Adicione um novo link pessoal ou à disciplina" %>
</div>
<%= render_navigation(level: 1) %>

app/views/shared/_message-block.html.erb
<%#
  Mensagem em bloco.

  Variáveis:
    type: o tipo (warning|success|info|busy).
    close: se deve mostrar o ícone de fechar.
    message: a messagem.
    button: algum botão, se necessário.
%>

<div class='<%= "message-block message-#{type} fade in" %>'>
  <% if close %>
    <span data-dismiss="alert" class="message-close">×</span>
  <% end %>
  <div class="message-block-content">
    <%= message %>
  </div>
  <% if button %>
    <div class="message-block-actions">
      <%= button %>
    </div>
  <% end %>
</div>

app/views/shared/_sub-tabs.html.erb
<div class="content-section">
  <p class="order-by">Ordene os links por:</p>
  <div class="center">
    <%= render_navigation(level: 2, renderer: :links) %>
  </div>
</div>

app/views/shared/_welcome-modal.html.erb
<div id="modal-welcome" class="modal hide">
  <div class="modal-header modal-header-gray">
    <h3>Bem-vindo ao Organize</h3>
  </div>
  <div class="modal-body">
    <p>Seja bem-vindo ao Organize. Esta ferramenta foi criada com o objetivo de ajudar professores e alunos a compartilharem links de apoio que auxiliem o estudo.</p>
    <p>Organize seus links de estudo e tenha sempre guardados os links importantes recomendado pelo professor. Comente e discuta com seus amigos de classe.</p>
  </div>
  <div class="modal-footer">
    <button data-dismiss="modal" class="button-default">Entrar</button>
  </div>
</div>